Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pvlib

df, meta = pvlib.iotools.get_bsrn(
    station='CAB',  # three letter code for the Cabauw station
    start=pd.Timestamp(2018,6,1),
    end=pd.Timestamp(2018,7,14),
    username=bsrn_username,  # replace with your own username
    password=bsrn_password,  # replace with your own password
)

show(df.head(), scrollX=True, scrollCollapse=True, paging=False, maxColumns=100, dom="tpr")
------------------

----- stderr -----
/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pvlib/iotools/bsrn.py:162: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  filenames = pd.date_range(
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTimeoutError[0m                              Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpvlib[39;00m
[0;32m----> 3[0m df, meta [38;5;241m=[39m [43mpvlib[49m[38;5;241;43m.[39;49m[43miotools[49m[38;5;241;43m.[39;49m[43mget_bsrn[49m[43m([49m
[1;32m      4[0m [43m    [49m[43mstation[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mCAB[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# three letter code for the Cabauw station[39;49;00m
[1;32m      5[0m [43m    [49m[43mstart[49m[38;5;241;43m=[39;49m[43mpd[49m[38;5;241;43m.[39;49m[43mTimestamp[49m[43m([49m[38;5;241;43m2018[39;49m[43m,[49m[38;5;241;43m6[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m)[49m[43m,[49m
[1;32m      6[0m [43m    [49m[43mend[49m[38;5;241;43m=[39;49m[43mpd[49m[38;5;241;43m.[39;49m[43mTimestamp[49m[43m([49m[38;5;241;43m2018[39;49m[43m,[49m[38;5;241;43m7[39;49m[43m,[49m[38;5;241;43m14[39;49m[43m)[49m[43m,[49m
[1;32m      7[0m [43m    [49m[43musername[49m[38;5;241;43m=[39;49m[43mbsrn_username[49m[43m,[49m[43m  [49m[38;5;66;43;03m# replace with your own username[39;49;00m
[1;32m      8[0m [43m    [49m[43mpassword[49m[38;5;241;43m=[39;49m[43mbsrn_password[49m[43m,[49m[43m  [49m[38;5;66;43;03m# replace with your own password[39;49;00m
[1;32m      9[0m [43m)[49m
[1;32m     11[0m show(df[38;5;241m.[39mhead(), scrollX[38;5;241m=[39m[38;5;28;01mTrue[39;00m, scrollCollapse[38;5;241m=[39m[38;5;28;01mTrue[39;00m, paging[38;5;241m=[39m[38;5;28;01mFalse[39;00m, maxColumns[38;5;241m=[39m[38;5;241m100[39m, dom[38;5;241m=[39m[38;5;124m"[39m[38;5;124mtpr[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pvlib/iotools/bsrn.py:167[0m, in [0;36mget_bsrn[0;34m(station, start, end, username, password, logical_records, save_path)[0m
[1;32m    162[0m filenames [38;5;241m=[39m pd[38;5;241m.[39mdate_range(
[1;32m    163[0m     start, end[38;5;241m.[39mreplace(day[38;5;241m=[39m[38;5;241m1[39m) [38;5;241m+[39m pd[38;5;241m.[39mDateOffset(months[38;5;241m=[39m[38;5;241m1[39m), freq[38;5;241m=[39m[38;5;124m'[39m[38;5;124m1M[39m[38;5;124m'[39m)\
[1;32m    164[0m     [38;5;241m.[39mstrftime([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mstation[38;5;132;01m}[39;00m[38;5;124m%m%y.dat.gz[39m[38;5;124m"[39m)[38;5;241m.[39mtolist()
[1;32m    166[0m [38;5;66;03m# Create FTP connection[39;00m
[0;32m--> 167[0m [38;5;28;01mwith[39;00m [43mftplib[49m[38;5;241;43m.[39;49m[43mFTP[49m[43m([49m[43mBSRN_FTP_URL[49m[43m,[49m[43m [49m[43musername[49m[43m,[49m[43m [49m[43mpassword[49m[43m)[49m [38;5;28;01mas[39;00m ftp:
[1;32m    168[0m     [38;5;66;03m# Change to station sub-directory (checks that the station exists)[39;00m
[1;32m    169[0m     [38;5;28;01mtry[39;00m:
[1;32m    170[0m         ftp[38;5;241m.[39mcwd([38;5;124mf[39m[38;5;124m'[39m[38;5;124m/[39m[38;5;132;01m{[39;00mstation[38;5;132;01m}[39;00m[38;5;124m'[39m)

File [0;32m/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/ftplib.py:121[0m, in [0;36mFTP.__init__[0;34m(self, host, user, passwd, acct, timeout, source_address, encoding)[0m
[1;32m    119[0m [38;5;28mself[39m[38;5;241m.[39mtimeout [38;5;241m=[39m timeout
[1;32m    120[0m [38;5;28;01mif[39;00m host:
[0;32m--> 121[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43mhost[49m[43m)[49m
[1;32m    122[0m     [38;5;28;01mif[39;00m user:
[1;32m    123[0m         [38;5;28mself[39m[38;5;241m.[39mlogin(user, passwd, acct)

File [0;32m/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/ftplib.py:158[0m, in [0;36mFTP.connect[0;34m(self, host, port, timeout, source_address)[0m
[1;32m    156[0m     [38;5;28mself[39m[38;5;241m.[39msource_address [38;5;241m=[39m source_address
[1;32m    157[0m sys[38;5;241m.[39maudit([38;5;124m"[39m[38;5;124mftplib.connect[39m[38;5;124m"[39m, [38;5;28mself[39m, [38;5;28mself[39m[38;5;241m.[39mhost, [38;5;28mself[39m[38;5;241m.[39mport)
[0;32m--> 158[0m [38;5;28mself[39m[38;5;241m.[39msock [38;5;241m=[39m [43msocket[49m[38;5;241;43m.[39;49m[43mcreate_connection[49m[43m([49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhost[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mport[49m[43m)[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mtimeout[49m[43m,[49m
[1;32m    159[0m [43m                                     [49m[43msource_address[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msource_address[49m[43m)[49m
[1;32m    160[0m [38;5;28mself[39m[38;5;241m.[39maf [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msock[38;5;241m.[39mfamily
[1;32m    161[0m [38;5;28mself[39m[38;5;241m.[39mfile [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msock[38;5;241m.[39mmakefile([38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m, encoding[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mencoding)

File [0;32m/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/socket.py:865[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address, all_errors)[0m
[1;32m    863[0m [38;5;28;01mtry[39;00m:
[1;32m    864[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m all_errors:
[0;32m--> 865[0m         [38;5;28;01mraise[39;00m exceptions[[38;5;241m0[39m]
[1;32m    866[0m     [38;5;28;01mraise[39;00m ExceptionGroup([38;5;124m"[39m[38;5;124mcreate_connection failed[39m[38;5;124m"[39m, exceptions)
[1;32m    867[0m [38;5;28;01mfinally[39;00m:
[1;32m    868[0m     [38;5;66;03m# Break explicitly a reference cycle[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/socket.py:850[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address, all_errors)[0m
[1;32m    848[0m [38;5;28;01mif[39;00m source_address:
[1;32m    849[0m     sock[38;5;241m.[39mbind(source_address)
[0;32m--> 850[0m [43msock[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43msa[49m[43m)[49m
[1;32m    851[0m [38;5;66;03m# Break explicitly a reference cycle[39;00m
[1;32m    852[0m exceptions[38;5;241m.[39mclear()

[0;31mTimeoutError[0m: [Errno 110] Connection timed out

